config/routes.rb
Rrhh::Application.routes.draw do
  get "estadisticas/index"
  get "estadisticas/indiv"
  scope '(:locale)' do
    resources :ciudades
    resources :permisologia_configuraciones
    resources :permisologias_menu
    resources :configuraciones
    resources :menus
    resources :objetivos
    resources :estados
    resources :proyectos do
      get :autocomplete_prospecto_apellido, :on => :collection
      get :autocomplete_usuario, :on => :collection
    end
    get "calendario/index"
    resources :cartas do
      get :autocomplete_prospecto_apellido, :on => :collection
    end
    get 'upload' => 'cartas'
    get 'obj_proyecto' => 'objetivos'
    post 'upload_file' => 'cartas'
    get 'config_func' => 'admin'
    get 'permisologia' => 'roles'
    post 'updatePermisologia' => 'roles'
    resources :notas_telefonicas do
      get :autocomplete_prospecto_apellido, :on => :collection
    end
    resources :usuarios
    resources :roles
    resources :cargos
    resources :prospectos do
      get :autocomplete_prospecto_apellido, :on => :collection
    end
    resources :edociviles
    resources :tipos
    resources :tipologias
    resources :entrenamientos
    resources :habilidades
    resources :areas
    resources :organizaciones
    get 'admin' => 'admin#index'
    controller :sesiones do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end
    resources :usuarios
    get 'prospectos/filtrar_prospectos'
    get 'inicio' => 'inicio#olvido_clave'
    post 'inicio' => 'inicio#olvido_clave'
    root 'sesiones#new'

  end
end

app/models/area.rb
class Area < ActiveRecord::Base
	has_many :prospecto
 	validates :nombre, presence: true
	validates :nombre, uniqueness: true		
end

app/models/carta.rb
class Carta < ActiveRecord::Base
  validates :cuerpo,:prospecto, presence: true, on: :create
  belongs_to :usuario
  belongs_to :prospecto
end

app/models/ciudad.rb
class Ciudad < ActiveRecord::Base
	has_many :prospecto
 	validates :nombre, presence: true
	validates :nombre, uniqueness: true
end

app/models/edocivil.rb
class Edocivil < ActiveRecord::Base
	has_many :prospecto
 	validates :nombre, presence: true
	validates :nombre, uniqueness: true		
end

app/models/estado.rb
class Estado < ActiveRecord::Base
	has_many :objetivo
 	validates :nombre, presence: true
	validates :nombre, uniqueness: true
end

app/models/habilidad.rb
class Habilidad < ActiveRecord::Base
	has_many :prospecto
 	validates :nombre, presence: true
	validates :nombre, uniqueness: true		
end

app/models/menu.rb
class Menu < ActiveRecord::Base
end

app/models/objetivo.rb
class Objetivo < ActiveRecord::Base
  validates :titulo, :cuerpo, presence: true
  belongs_to :estado
  belongs_to :proyecto
end

app/models/organizacion.rb
class Organizacion < ActiveRecord::Base
	has_many :prospecto
 	validates :nombre, presence: true
	validates :nombre, uniqueness: true
end

app/models/prospecto.rb
class Prospecto < ActiveRecord::Base
  validates :nombre, :direccion, :telefono, :correo, :edad, :hijos, :deudas, presence: true
  validates :correo, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i , message: "formato non valido"}
  validates :edad, numericality: { only_integer: true, greater_than: 15 }
  validates :hijos, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :deudas, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  belongs_to :habilidad
  belongs_to :entrenamiento
  belongs_to :organizacion, :class_name => "Organizacion"
  belongs_to :organizacionpublic, :class_name => "Organizacion"
  belongs_to :tipo
  belongs_to :edocivil
  belongs_to :area
  belongs_to :ciudad
  belongs_to :tipologia
  belongs_to :usuario
  validates :nombre, :direccion, :telefono, :correo, :edad, :hijos, :deudas, presence: true
  has_many :notas_telefonicas, :dependent => :delete_all
  has_many :cartas, :dependent => :delete_all
  has_many :proyectos, :dependent => :destroy

def apellido_nombre
  self.apellido+' '+self.nombre
end

end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
  belongs_to :prospecto
  belongs_to :usuario
  has_many :objetivos, :dependent => :delete_all
  #after_create :objDefault
  validates :nombre,:prospecto_id, presence: true

  #Objetivo por defecto
  # def objDefault
  # 	objetivo = Objetivo.new
  # 	objetivo.proyecto_id = self.id
  # 	objetivo.estado_id = 1
  # 	objetivo.save
  # end
end

app/models/rol.rb
class Rol < ActiveRecord::Base
	has_many :usuario	
	validates :nombre, presence: true
	validates :nombre, uniqueness: true
end

app/models/tipo.rb
class Tipo < ActiveRecord::Base
	has_many :prospecto
 	validates :nombre, presence: true
	validates :nombre, uniqueness: true	
end

app/models/tipologia.rb
class Tipologia < ActiveRecord::Base
	has_many :prospecto
 	validates :nombre, presence: true
	validates :nombre, uniqueness: true
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	validates :nombre_usuario, :nombre_completo, :correo, :password_digest, presence: true
	validates :nombre_usuario, uniqueness: true
	validates :correo, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i , message: "formato non valido"}
	belongs_to :rol
	has_secure_password
	after_destroy :ensure_an_admin_remains
	has_many :nota_telefonicas
	has_many :carta
	has_many :proyecto
	has_many :prospecto

	def self.encriptar(password_digest)
		BCrypt::Password.create(password_digest)
	end

	private
	def ensure_an_admin_remains
		if Usuario.count.zero?
			raise "No se puede eliminar el último usuario"
		end
	end
end

app/controllers/permisologias_menu_controller.rb
class PermisologiasMenuController < ApplicationController
  before_action :set_permisologia_menu, only: [:show, :edit, :update, :destroy]

  # GET /permisologias_menu
  # GET /permisologias_menu.json
  def index
    @permisologias_menu = PermisologiaMenu.all
  end

  # GET /permisologias_menu/1
  # GET /permisologias_menu/1.json
  def show
  end

  # GET /permisologias_menu/new
  def new
    @permisologia_menu = PermisologiaMenu.new
  end

  # GET /permisologias_menu/1/edit
  def edit
  end

  # POST /permisologias_menu
  # POST /permisologias_menu.json
  def create
    @permisologia_menu = PermisologiaMenu.new(permisologia_menu_params)

    respond_to do |format|
      if @permisologia_menu.save
        format.html { redirect_to @permisologia_menu, notice: 'Permisologia menu was successfully created.' }
        format.json { render action: 'show', status: :created, location: @permisologia_menu }
      else
        format.html { render action: 'new' }
        format.json { render json: @permisologia_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permisologias_menu/1
  # PATCH/PUT /permisologias_menu/1.json
  def update
    respond_to do |format|
      if @permisologia_menu.update(permisologia_menu_params)
        format.html { redirect_to @permisologia_menu, notice: 'Permisologia menu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @permisologia_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permisologias_menu/1
  # DELETE /permisologias_menu/1.json
  def destroy
    @permisologia_menu.destroy
    respond_to do |format|
      format.html { redirect_to permisologias_menu_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permisologia_menu
      @permisologia_menu = PermisologiaMenu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permisologia_menu_params
      params.require(:permisologia_menu).permit(:rol_id, :menu_id, :permiso)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/permisologias_menu_helper.rb
module PermisologiasMenuHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/permisologias_menu/_form.html.erb
<%= form_for(@permisologia_menu) do |f| %>
  <% if @permisologia_menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@permisologia_menu.errors.count, "error") %> prohibited this permisologia_menu from being saved:</h2>

      <ul>
      <% @permisologia_menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rol %><br>
    <%= f.text_field :rol %>
  </div>
  <div class="field">
    <%= f.label :menu %><br>
    <%= f.text_field :menu %>
  </div>
  <div class="field">
    <%= f.label :permiso %><br>
    <%= f.check_box :permiso %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/permisologias_menu/edit.html.erb
<h1>Editing permisologia_menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @permisologia_menu %> |
<%= link_to 'Back', permisologias_menu_path %>

app/views/permisologias_menu/index.html.erb
<h1>Listing permisologias_menu</h1>

<table>
  <thead>
    <tr>
      <th>Rol</th>
      <th>Menu</th>
      <th>Permiso</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @permisologias_menu.each do |permisologia_menu| %>
      <tr>
        <td><%= permisologia_menu.rol %></td>
        <td><%= permisologia_menu.menu %></td>
        <td><%= permisologia_menu.permiso %></td>
        <td><%= link_to 'Show', permisologia_menu %></td>
        <td><%= link_to 'Edit', edit_permisologia_menu_path(permisologia_menu) %></td>
        <td><%= link_to 'Destroy', permisologia_menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Permisologia menu', new_permisologia_menu_path %>

app/views/permisologias_menu/new.html.erb
<h1>New permisologia_menu</h1>

<%= render 'form' %>

<%= link_to 'Back', permisologias_menu_path %>

app/views/permisologias_menu/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rol:</strong>
  <%= @permisologia_menu.rol %>
</p>

<p>
  <strong>Menu:</strong>
  <%= @permisologia_menu.menu %>
</p>

<p>
  <strong>Permiso:</strong>
  <%= @permisologia_menu.permiso %>
</p>

<%= link_to 'Edit', edit_permisologia_menu_path(@permisologia_menu) %> |
<%= link_to 'Back', permisologias_menu_path %>