config/routes.rb
Rrhh::Application.routes.draw do
  get "estadisticas/index"
  get "estadisticas/indiv"
  scope '(:locale)' do
    resources :ciudades
    resources :permisologia_configuraciones
    resources :permisologias_menu
    resources :configuraciones
    resources :menus
    resources :objetivos
    resources :estados
    resources :proyectos do
      get :autocomplete_prospecto_apellido, :on => :collection
      get :autocomplete_usuario, :on => :collection
    end
    get "calendario/index"
    resources :cartas do
      get :autocomplete_prospecto_apellido, :on => :collection
    end
    get 'upload' => 'cartas'
    get 'obj_proyecto' => 'objetivos'
    post 'upload_file' => 'cartas'
    get 'config_func' => 'admin'
    get 'permisologia' => 'roles'
    post 'updatePermisologia' => 'roles'
    resources :notas_telefonicas do
      get :autocomplete_prospecto_apellido, :on => :collection
    end
    resources :usuarios
    resources :roles
    resources :cargos
    resources :prospectos do
      get :autocomplete_prospecto_apellido, :on => :collection
    end
    resources :edociviles
    resources :tipos
    resources :tipologias
    resources :entrenamientos
    resources :habilidades
    resources :areas
    resources :organizaciones
    get 'admin' => 'admin#index'
    controller :sesiones do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end
    resources :usuarios
    get 'prospectos/filtrar_prospectos'
    get 'inicio' => 'inicio#olvido_clave'
    post 'inicio' => 'inicio#olvido_clave'
    root 'sesiones#new'

  end
end

app/models/prospecto.rb
class Prospecto < ActiveRecord::Base
  validates :nombre, :direccion, :telefono, :correo, :edad, :hijos, :deudas, presence: true
  validates :correo, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i , message: "formato non valido"}
  validates :edad, numericality: { only_integer: true, greater_than: 15 }
  validates :hijos, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :deudas, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  belongs_to :habilidad
  belongs_to :entrenamiento
  belongs_to :organizacion, :class_name => "Organizacion"
  belongs_to :organizacionpublic, :class_name => "Organizacion"
  belongs_to :tipo
  belongs_to :edocivil
  belongs_to :area
  belongs_to :ciudad
  belongs_to :tipologia
  belongs_to :usuario
  validates :nombre, :direccion, :telefono, :correo, :edad, :hijos, :deudas, presence: true
  has_many :notas_telefonicas, :dependent => :delete_all
  has_many :cartas, :dependent => :delete_all
  has_many :proyectos, :dependent => :destroy

def apellido_nombre
  self.apellido+' '+self.nombre
end

end

app/controllers/prospectos_controller.rb
class ProspectosController < ApplicationController
  before_action :set_prospecto, only: [:show, :edit, :update, :destroy]

  # autocomplete :prospecto, :apellido,:extra_data => [:id]
  def autocomplete_prospecto_apellido
    term = params[:term].upcase
    prospectos = Prospecto.where("upper(apellido) LIKE ? or upper(nombre) LIKE ? or upper(concat(apellido,' ', nombre)) like ?","%#{term}%","%#{term}%","%#{term}%").order(:apellido)
    #prospectos = Prospecto.where("apellido LIKE ?","%#{term}%").order(:apellido)
    render :json => prospectos.map { |prospecto| {:id => prospecto.id, :label => prospecto.apellido_nombre, :value => prospecto.apellido_nombre} }
  end

  # GET /prospectos
  # GET /prospectos.json
  def index
    @prospectos = Prospecto.all
    if !params[:prospecto].blank?
      @prospectos = @prospectos.where(id: params[:prospecto])
    else
      if !params[:area].blank?
        @prospectos = @prospectos.where(area_id: params[:area])
      end
      if !params[:organizacion].blank?
        @prospectos = @prospectos.where(organizacion_id: params[:organizacion])
      end
      if !params[:habilidad].blank?
        @prospectos = @prospectos.where(habilidad_id: params[:habilidad])
      end
      if !params[:entrenamiento].blank?
        @prospectos = @prospectos.where(entrenamiento_id: params[:entrenamiento])
      end
      if !params[:tipologia].blank?
        @prospectos = @prospectos.where(tipologia_id: params[:tipologia])
      end
      if !params[:tipo].blank?
        @prospectos = @prospectos.where(tipo_id: params[:tipo])
      end
      if !params[:edocivil].blank?
        @prospectos = @prospectos.where(edocivil_id: params[:edocivil])
      end
    end
    @prospectos = @prospectos.paginate(:page => params[:page], :per_page => 10).order('nombre ASC')
    @cantidad = @prospectos.count
    @area = Area.all
    @organizacion = Organizacion.all
    @habilidad = Habilidad.all
    @entrenamiento = Entrenamiento.all
    @tipologia = Tipologia.all
    @tipo = Tipo.all
    @edocivil = Edocivil.all

    respond_to do |format|
      format.html do
        unless params[:prospecto].blank?
          if params[:commit] == "X"
            redirect_to prospectos_path
          end
        end
      end
      format.pdf do
        pdf = PdfGenerator.new
        pdf.list_prospecto(@prospectos, @cantidad)
        send_data pdf.render, filename: "prospecto_list.pdf",type: "application/pdf",disposition: "inline"
      end
    end

  end

  def filtrar_prospectos
        @prospectos = Prospecto.joins(:area).where(area_id: params[:area_id])
  end

  def simple

  end

  # GET /prospectos/1
  # GET /prospectos/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        prospecto = Prospecto.find(params[:id])
        pdf = PdfGenerator.new
        pdf.show_prospecto(prospecto)
        send_data pdf.render, filename: "prospecto_#{params[:id]}.pdf",type: "application/pdf",disposition: "inline"
      end
    end
  end

  # GET /prospectos/new
  def new
    @prospecto = Prospecto.new
  end

  # GET /prospectos/1/edit
  def edit
  end

  # POST /prospectos
  # POST /prospectos.json
  def create
    @prospecto = Prospecto.new(prospecto_params)

    respond_to do |format|
      if @prospecto.save
        format.html { redirect_to @prospecto, notice: "Il Prospetto: #{@prospecto.apellido_nombre}  è stato creato con successo." }
        format.json { render action: 'show', status: :created, location: @prospecto }
      else
        format.html { render action: 'new' }
        format.json { render json: @prospecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prospectos/1
  # PATCH/PUT /prospectos/1.json
  def update
    respond_to do |format|
      if @prospecto.update(prospecto_params)
        format.html { redirect_to @prospecto, notice: "Il Prospetto: #{@prospecto.apellido_nombre} è stato aggiornato con successo." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @prospecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prospectos/1
  # DELETE /prospectos/1.json
  def destroy

    @prospecto.destroy
    respond_to do |format|
      format.html { redirect_to prospectos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prospecto
      @prospecto = Prospecto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prospecto_params
      params.require(:prospecto).permit(:nombre, :direccion, :telefono, :correo, :habilidad_id, :entrenamiento_id, :organizacion_id, :tipo_id, :edad, :edocivil_id, :hijos, :deudas, :area_id, :apellido, :ciudad_id, :zona_postal, :tipologia_id, :public, :organizacionpublic_id, :usuario_id)
    end

end

app/helpers/prospectos_helper.rb
module ProspectosHelper
end

app/views/prospectos/_form.html.erb
<%= form_for(@prospecto) do |f| %>
<script type="text/javascript">
  $(document).ready(function(){
    $("#prospecto_tipologia_id").change(function(){
        if ($(this).val() == 2)
        {
            $(".fieldOrgPublic").show();
        }else
        {
            $(".fieldOrgPublic").hide();
            $("#prospecto_public").prop('checked',false);
        }
    });
  });
</script>
  <% if @prospecto.errors.any? %>
    <div id="error_explanation">
      <h2><%=raw t('errors.template.header', count: @prospecto.errors.count, model: "prospetto") %></h2>
      <ul>
      <% @prospecto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="row">
    <div class="col-xs-4">
    <% if params[:action] == "new" %>
      <%= f.hidden_field(:usuario_id, value: session[:usuario_id] ) %>
    <% else %>
      <%= f.label :usuario %>: <%= f.label Usuario.find_by(id: @prospecto.usuario_id).nombre_completo %><br>
      <%= f.hidden_field :usuario_id, value: @prospecto.usuario_id %>
    <% end %>
  </div></div>
    <div class="row">
    <div class="col-xs-4">
    <%= f.label :apellido, id:"color-etiq" %><br>
    <%= f.text_field :apellido, class: 'form-control placeholder-no-fix', placeholder: 'E.g: Pirlo Andrea', autocomplete: 'off' %>
  </div></div>
    <div class="row">
    <div class="col-xs-4">
    <%= f.label :nombre, id:"color-etiq" %><br>
    <%= f.text_field :nombre, class: 'form-control placeholder-no-fix', placeholder: 'E.g: Pirlo Andrea', autocomplete: 'off' %>
  </div></div>
    <div class="row">
    <div class="col-xs-4">
    <%= f.label :direccion, id:"color-etiq" %><br>
    <%= f.text_field :direccion,  class:"form-control" %>
  </div></div>
  <div class="row">
    <div class="col-xs-4">
    <%= f.label :ciudad, id:"color-etiq" %><br>
    <%= f.collection_select :ciudad_id, Ciudad.all, :id, :nombre, {prompt: 'Selezionare'},{class: 'form-control'} %>
    </div>
  </div>
    <div class="row">
    <div class="col-xs-4">
    <%= f.label :zona_postal, id:"color-etiq" %><br>
    <%= f.text_field :zona_postal,  class:"form-control" %>
  </div></div>
    <div class="row">
    <div class="col-xs-4">
    <%= f.label :telefono, id:"color-etiq" %><br>
    <%= f.text_field :telefono,  class:"form-control" %>
  </div></div>
    <div class="row">
    <div class="col-xs-4">
    <%= f.label :correo, id:"color-etiq" %><br>
    <%= f.text_field :correo,  class:"form-control" %>
  </div></div>
    <div class="row">
    <div class="col-xs-4">
    <%= f.label :habilidad, id:"color-etiq" %><br>
    <%= f.collection_select :habilidad_id, Habilidad.all, :id, :nombre, {prompt: 'Selezionare'},{class: 'form-control'} %>
  </div></div>
    <div class="row">
    <div class="col-xs-4">
    <%= f.label :entrenamiento, id:"color-etiq" %><br>
    <%= f.collection_select :entrenamiento_id, Entrenamiento.all, :id, :nombre, {prompt: 'Selezionare'},{class: 'form-control'} %>
  </div></div>
    <div class="row">
    <div class="col-xs-4">
    <%= f.label :tipologia, id:"color-etiq" %><br>
    <%= f.collection_select :tipologia_id, Tipologia.all, :id, :nombre, {prompt: 'Selezionare'},{class: 'form-control'} %>
  </div></div>
    <div class="row">
    <div class="col-xs-4">
    <%= f.label :organizacion, id:"color-etiq" %><br>
    <%= f.collection_select :organizacion_id, Organizacion.all, :id, :nombre, {prompt: 'Selezionare'},{class: 'form-control'} %>
  </div></div>
  <div class="fieldOrgPublic" <% unless @prospecto.tipologia_id == 2 %>style="display:none;"<% end %>>
    <div class="row">
      <div class="col-xs-4">
        <%= f.label "Si trova nelle linee del pubblico?", id:"color-etiq" %><br>
        <%= f.check_box :public %>
      </div>
    </div>
  </div>
  <div class="fieldOrgPublic" <% unless @prospecto.tipologia_id == 2 %>style="display:none;"<% end %>>
    <div class="row">
      <div class="col-xs-4">
        <%= f.label "In quale organizazzione?", id:"color-etiq" %><br>
        <%= f.collection_select :organizacionpublic_id, Organizacion.all, :id, :nombre, {prompt: 'Selezionare'},{class: 'form-control'} %>
      </div>
    </div>
  </div>
    <div class="row">
    <div class="col-xs-4">
    <%= f.label :tipo, id:"color-etiq" %><br>
    <%= f.collection_select :tipo_id, Tipo.all, :id, :nombre, {prompt: 'Selezionare'},{class: 'form-control'} %>
  </div></div>
    <div class="row">
    <div class="col-xs-4">
    <%= f.label :edad, id:"color-etiq" %><br>
    <%= f.number_field :edad,  class:"form-control" %>
  </div></div>
    <div class="row">
    <div class="col-xs-4">
    <%= f.label :edocivil, id:"color-etiq" %><br>
    <%= f.collection_select :edocivil_id, Edocivil.all, :id, :nombre, {prompt: 'Selezionare'},{class: 'form-control'} %>
  </div></div>
    <div class="row">
    <div class="col-xs-4">
    <%= f.label :hijos, id:"color-etiq" %><br>
    <%= f.number_field :hijos,  class:"form-control" %>
  </div></div>
  <%= f.label :deudas, id:"color-etiq" %><br>
    <div class="row">
    <div class="col-xs-4">
  <div class="input-group">
    <%= f.number_field :deudas,  class:"form-control" %>
    <span class="input-group-addon">€</span>
  </div></div></div>
    <div class="row">
    <div class="col-xs-4">
    <%= f.label :area, id:"color-etiq" %><br>
    <%= f.collection_select :area_id, Area.all, :id, :nombre, {prompt: 'Selezionare'},{class: 'form-control'}  %>
  </div></div>
  <br>
  <div class="actions">
    <%= f.submit t('.submit'), class: 'btn btn-default btn-md', id: 'btn-defecto' %>
  </div>

<% end %>

app/views/prospectos/edit.html.erb
<script>
$("#prp").addClass("start active");
</script>
<div class="panel-heading"><%= link_to content_tag(:span, '', class: 'glyphicon glyphicon-chevron-left'), prospectos_path, class: "lnk_back",title: 'Ritorno' %> &nbsp;&nbsp;Modifica Prospetto</div>
<div class="table-responsive">
	<br>
<%= render 'form' %> <%= link_to 'Mostrare', @prospecto, class: "btn btn-primary btn-sm", id: "color-blanco" %>

</div>

app/views/prospectos/index.html.erb
<%
  prospecto_au = ""
  unless params[:prospecto].blank?
    prospecto_au = Prospecto.find_by(id: params[:prospecto]).apellido_nombre
  end
%>
<style type="text/css">
  /*a:after { content:' [' attr(href) '] ';}*/
</style>
<script>
$("#prp").addClass("start active");
</script>

<% if @prospectos.count.zero? %>

  <div class="panel-heading" id="panel-heading-sep">
    <center><label id="color-etiq">nessuna nota telefonica da visualizzare</label></center>
  </div>
  <br>

    <div class="row">

      <% if params[:permiso_new] %>
        <% if params[:prospecto].blank? %>
          <div class="col-md-2"><%= link_to 'Nuovo Lettera', new_carta_path, class: 'btn btn-primary btn-sm', id: 'color-blanco' %></div>
        <% else %>
          <div class="col-md-2"><%= link_to 'Nuovo Lettera', new_carta_path(prospecto: params[:prospecto]), class: 'btn btn-primary btn-sm', id: 'color-blanco' %></div>
        <% end %>
      <% end %>
      <div class="col-md-10"><%= will_paginate @cartas, renderer: BootstrapPagination::Rails, :previous_label => "<<", :next_label => ">>" %></div>
    </div>


<% else %>

<div class="panel-heading" id="panel-heading-sep">Elenco Prospetti
<div class="row">
<br>
<%= form_tag("/prospectos", method: "get") do %>
  <div class="col-md-4"><%=autocomplete_field_tag "prospecto_au", prospecto_au, autocomplete_prospecto_apellido_prospectos_path, :update_elements => {:id => '#prospecto' }, :placeholder => "Inserisci prospetto", :size => 75, class: 'form-control' %></div>
  <%= hidden_field_tag "prospecto",params[:prospecto] %>
  <div class="col-md-8"><%= submit_tag "Ricerca", class: "btn btn-success btn-md" %>
  <% unless params[:prospecto].blank? %>&nbsp<%= submit_tag "X", class: "btn btn-danger btn-md" %><% end %>
<% end %></div>
</div>
<br />
<div class="row">
<%= form_tag("/prospectos", method: "get") do %>
  <div class="col-md-2" style="width: 13%;"><%= select_tag "tipo", options_from_collection_for_select(@tipo, "id", "nombre" , selected: params[:tipo]), prompt: 'Tipo:', class: 'form-control' %></div>
  <div class="col-md-2" style="width: 13%;"><%= select_tag "organizacion", options_from_collection_for_select(@organizacion, "id", "nombre", selected: params[:organizacion]), prompt: 'Organizzazione:', class: 'form-control' %></div>
  <div class="col-md-2" style="width: 13%;"><%= select_tag "habilidad", options_from_collection_for_select(@habilidad, "id", "nombre", selected: params[:habilidad]), prompt: 'Livello di caso:', class: 'form-control' %></div>
  <div class="col-md-2" style="width: 13%;"><%= select_tag "entrenamiento", options_from_collection_for_select(@entrenamiento, "id", "nombre", selected: params[:entrenamiento]), prompt: 'Livello di addestramento:', class: 'form-control' %></div>
  <div class="col-md-2" style="width: 13%;"><%= select_tag "tipologia", options_from_collection_for_select(@tipologia, "id", "nombre", selected: params[:tipologia]), prompt: 'Tipologia:', class: 'form-control' %></div>
  <div class="col-md-2" style="width: 13%;"><%= select_tag "edocivil", options_from_collection_for_select(@edocivil, "id", "nombre", selected: params[:edocivil]), prompt: 'Stato Civile:', class: 'form-control' %></div>
  <div class="col-md-2" style="width: 13%;"><%= select_tag "area", options_from_collection_for_select(@area, "id", "nombre", selected: params[:area]), prompt: 'Professione:', class: 'form-control' %></div>
  &nbsp&nbsp<%= submit_tag "Filtro", class: "btn btn-success btn-md" %>
<% end %>
</div>

</div>

<div class="table-responsive">
  <table class="table table-hover">
  <thead>
    <tr>
      <td>Cognome</td>
      <td>Nome</td>
      <td>Età</td>
      <td>Stato Civile</td>
      <td>Figli</td>
      <td>Debiti</td>
      <td>Città</td>
      <td>Teléfono</td>
      <td>Mail</td>
      <td></td>
      <% if params[:permiso_edit] %><th></th><% end %>
      <% if params[:permiso_delete] %><th></th><% end %>
    </tr>
  </thead>

  <tbody>
    <% @prospectos.each do |prospecto| %>
      <tr>
        <td><%= prospecto.apellido %></td>
        <td><%= prospecto.nombre %></td>
        <td><%= prospecto.edad %></td>
        <td><%unless prospecto.edocivil.blank?%><%= prospecto.edocivil.nombre %><% else %>Nessun valore<% end %></td>
        <td><%= prospecto.hijos %></td>
        <td><% if prospecto.deudas > 0 %><span class='glyphicon glyphicon-plus-sign' style='color:red;'></span><%else%><span class='glyphicon glyphicon-minus-sign' style='color:green;'></span><%end%></td>
        <td><%unless prospecto.ciudad.blank?%><%= prospecto.ciudad.nombre %><% else %>Nessun valore<% end %></td>
        <td><%= prospecto.telefono %></td>
        <td><%= prospecto.correo %></td>
        <td><%= link_to content_tag(:span, '', class: 'glyphicon glyphicon-folder-open'), prospecto, title: 'Mostrare', id: "acciones" %></td>
        <% if params[:permiso_edit] %><td><%= link_to content_tag(:span, '', class: 'glyphicon glyphicon-edit'), edit_prospecto_path(prospecto), title: 'Modifica', id: "acciones" %></td><% end %>
        <% if params[:permiso_delete] %><td><%= link_to content_tag(:span, '', class: 'glyphicon glyphicon-remove'), prospecto, title: 'Eliminare', id: "acciones", method: :delete, data: { confirm: 'Sei sicuro?' } %></td><% end %>
      </tr>
    <% end %>
  </tbody>

  <tfoot>
    <tr>
      <td>Totale Prospetti: <b><%= @cantidad %></b></td>

      <td><%= will_paginate @prospectos, renderer: BootstrapPagination::Rails, :previous_label => "<<", :next_label => ">>" %></td>


    </tr>
    <tr>
      <% if params[:permiso_new] %>
      <td><%= link_to 'Nuovo Prospetto', new_prospecto_path, class: 'btn btn-primary btn-sm', id: 'color-blanco' %></td>
      <% end %>
      <% if params[:commit].blank? %>
      <td>
        <%= link_to content_tag(:span, ' Stampa', class: 'glyphicon glyphicon-print'), prospectos_path(:format => "pdf"), class: 'btn btn-default btn-sm', target: "_blank"%>
      </td>
      <% else %>
      <td>
        <%= link_to content_tag(:span, ' Stampa', class: 'glyphicon glyphicon-print'), prospectos_path(:format => "pdf", tipo: params[:tipo],organizacion: params[:organizacion],habilidad: params[:habilidad],entrenamiento: params[:entrenamiento],tipologia: params[:tipologia],edocivil: params[:edocivil],area: params[:area]), :target => "_blank", class: 'btn btn-default btn-sm' %>
      </td>
      <% end %>
    </tr>
  </tfoot>

</table>

</div>

<% end %>

app/views/prospectos/new.html.erb
<script>
$("#prp").addClass("start active");
</script>
<div class="panel-heading" id="panel-heading-sep">
	<%= link_to content_tag(:span, '', class: 'glyphicon glyphicon-chevron-left'), prospectos_path, class: "lnk_back",title: 'Ritorno' %> &nbsp;&nbsp;
	<b>Nuovo Prospetto</b>
</div>
<div class="table-responsive">
<%= render 'form' %>

</div>

app/views/prospectos/show.html.erb
<script>
$("#prp").addClass("start active");
</script>
<div class="panel-heading" id="panel-heading-sep">
  <%= link_to content_tag(:span, '', class: 'glyphicon glyphicon-chevron-left'), prospectos_path, class: "lnk_back",title: 'Ritorno' %> &nbsp;&nbsp;
  <b>Prospetto dettagli <%= @prospecto.nombre %></b>
</div>



<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Tipo</th>
        <th>Cognome Nome</th>
        <th>Età</th>
        <th>Stato Civile</th>
        <th>Figli</th>
        <th>Debiti</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%unless @prospecto.tipo.blank?%><%= @prospecto.tipo.nombre %><% else %>Nessun valore<% end %></td>
        <td><%= @prospecto.apellido_nombre %></td>
        <td><%= @prospecto.edad %></td>
        <td><%unless @prospecto.edocivil.blank?%><%= @prospecto.edocivil.nombre %><% else %>Nessun valore<% end %></td>
        <td><%= @prospecto.hijos %></td>
        <td><%= @prospecto.deudas %>&nbsp€</td>
      </tr>
    </tbody>
  </table>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Indirizzo</th>
        <th>Città</th>
        <th>Codice Postale</th>
        <th>Telefono</th>
        <th>Mail</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @prospecto.direccion %></td>
        <td><%unless @prospecto.ciudad.blank?%><%= @prospecto.ciudad.nombre %><% else %>Nessun valore<% end %></td>
        <td><%= @prospecto.zona_postal %></td>
        <td><%= @prospecto.telefono %></td>
        <td><%= @prospecto.correo %></td>
      </tr>
    </tbody>
  </table>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Staff</th>
        <th>Exstaff</th>
        <th>Organizzazione</th>
        <th>Livello di caso</th>
        <th>Livello di addestramento</th>
        <th>Professione</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%unless @prospecto.tipologia.blank?%><%= @prospecto.tipologia.nombre %><% else %>Nessun valore<% end %></td>
        <td><%unless @prospecto.tipologia.blank?%><%= @prospecto.tipologia.nombre %><% else %>Nessun valore<% end %></td>
        <td><%unless @prospecto.organizacion.blank?%><%= @prospecto.organizacion.nombre %><% else %>Nessun valore<% end %></td>
        <td><%unless @prospecto.habilidad.blank?%><%= @prospecto.habilidad.nombre %><% else %>Nessun valore<% end %></td>
        <td><%unless @prospecto.entrenamiento.blank?%><%= @prospecto.entrenamiento.nombre %><% else %>Nessun valore<% end %></td>
        <td><%unless @prospecto.area.blank?%><%= @prospecto.area.nombre %><% else %>Nessun valore<% end %></td>
      </tr>
    </tbody>
  </table>
  <%= link_to content_tag(:span, ' Stampa', class: 'glyphicon glyphicon-print'), prospecto_path(:format => "pdf"), class: 'btn btn-default btn-sm',target: "_blank" %>
</div>