config/routes.rb
Rrhh::Application.routes.draw do
  get "estadisticas/index"
  get "estadisticas/indiv"
  scope '(:locale)' do
    resources :ciudades
    resources :permisologia_configuraciones
    resources :permisologias_menu
    resources :configuraciones
    resources :menus
    resources :objetivos
    resources :estados
    resources :proyectos do
      get :autocomplete_prospecto_apellido, :on => :collection
      get :autocomplete_usuario, :on => :collection
    end
    get "calendario/index"
    resources :cartas do
      get :autocomplete_prospecto_apellido, :on => :collection
    end
    get 'upload' => 'cartas'
    get 'obj_proyecto' => 'objetivos'
    post 'upload_file' => 'cartas'
    get 'config_func' => 'admin'
    get 'permisologia' => 'roles'
    post 'updatePermisologia' => 'roles'
    resources :notas_telefonicas do
      get :autocomplete_prospecto_apellido, :on => :collection
    end
    resources :usuarios
    resources :roles
    resources :cargos
    resources :prospectos do
      get :autocomplete_prospecto_apellido, :on => :collection
    end
    resources :edociviles
    resources :tipos
    resources :tipologias
    resources :entrenamientos
    resources :habilidades
    resources :areas
    resources :organizaciones
    get 'admin' => 'admin#index'
    controller :sesiones do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end
    resources :usuarios
    get 'prospectos/filtrar_prospectos'
    get 'inicio' => 'inicio#olvido_clave'
    post 'inicio' => 'inicio#olvido_clave'
    root 'sesiones#new'

  end
end

app/models/area.rb
class Area < ActiveRecord::Base
	has_many :prospecto
 	validates :nombre, presence: true
	validates :nombre, uniqueness: true		
end

app/models/carta.rb
class Carta < ActiveRecord::Base
  validates :cuerpo,:prospecto, presence: true, on: :create
  belongs_to :usuario
  belongs_to :prospecto
end

app/models/ciudad.rb
class Ciudad < ActiveRecord::Base
	has_many :prospecto
 	validates :nombre, presence: true
	validates :nombre, uniqueness: true
end

app/models/configuracion.rb
class Configuracion < ActiveRecord::Base
end

app/models/edocivil.rb
class Edocivil < ActiveRecord::Base
	has_many :prospecto
 	validates :nombre, presence: true
	validates :nombre, uniqueness: true		
end

app/models/estado.rb
class Estado < ActiveRecord::Base
	has_many :objetivo
 	validates :nombre, presence: true
	validates :nombre, uniqueness: true
end

app/models/habilidad.rb
class Habilidad < ActiveRecord::Base
	has_many :prospecto
 	validates :nombre, presence: true
	validates :nombre, uniqueness: true		
end

app/models/menu.rb
class Menu < ActiveRecord::Base
end

app/models/objetivo.rb
class Objetivo < ActiveRecord::Base
  validates :titulo, :cuerpo, presence: true
  belongs_to :estado
  belongs_to :proyecto
end

app/models/organizacion.rb
class Organizacion < ActiveRecord::Base
	has_many :prospecto
 	validates :nombre, presence: true
	validates :nombre, uniqueness: true
end

app/models/prospecto.rb
class Prospecto < ActiveRecord::Base
  validates :nombre, :direccion, :telefono, :correo, :edad, :hijos, :deudas, presence: true
  validates :correo, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i , message: "formato non valido"}
  validates :edad, numericality: { only_integer: true, greater_than: 15 }
  validates :hijos, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :deudas, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  belongs_to :habilidad
  belongs_to :entrenamiento
  belongs_to :organizacion, :class_name => "Organizacion"
  belongs_to :organizacionpublic, :class_name => "Organizacion"
  belongs_to :tipo
  belongs_to :edocivil
  belongs_to :area
  belongs_to :ciudad
  belongs_to :tipologia
  belongs_to :usuario
  validates :nombre, :direccion, :telefono, :correo, :edad, :hijos, :deudas, presence: true
  has_many :notas_telefonicas, :dependent => :delete_all
  has_many :cartas, :dependent => :delete_all
  has_many :proyectos, :dependent => :destroy

def apellido_nombre
  self.apellido+' '+self.nombre
end

end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
  belongs_to :prospecto
  belongs_to :usuario
  has_many :objetivos, :dependent => :delete_all
  #after_create :objDefault
  validates :nombre,:prospecto_id, presence: true

  #Objetivo por defecto
  # def objDefault
  # 	objetivo = Objetivo.new
  # 	objetivo.proyecto_id = self.id
  # 	objetivo.estado_id = 1
  # 	objetivo.save
  # end
end

app/models/rol.rb
class Rol < ActiveRecord::Base
	has_many :usuario	
	validates :nombre, presence: true
	validates :nombre, uniqueness: true
end

app/models/tipo.rb
class Tipo < ActiveRecord::Base
	has_many :prospecto
 	validates :nombre, presence: true
	validates :nombre, uniqueness: true	
end

app/models/tipologia.rb
class Tipologia < ActiveRecord::Base
	has_many :prospecto
 	validates :nombre, presence: true
	validates :nombre, uniqueness: true
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	validates :nombre_usuario, :nombre_completo, :correo, :password_digest, presence: true
	validates :nombre_usuario, uniqueness: true
	validates :correo, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i , message: "formato non valido"}
	belongs_to :rol
	has_secure_password
	after_destroy :ensure_an_admin_remains
	has_many :nota_telefonicas
	has_many :carta
	has_many :proyecto
	has_many :prospecto

	def self.encriptar(password_digest)
		BCrypt::Password.create(password_digest)
	end

	private
	def ensure_an_admin_remains
		if Usuario.count.zero?
			raise "No se puede eliminar el último usuario"
		end
	end
end

app/controllers/tipologias_controller.rb
class TipologiasController < ApplicationController
  before_action :set_tipologia, only: [:show, :edit, :update, :destroy]

  # GET /tipologias
  # GET /tipologias.json
  def index
    @tipologias = Tipologia.paginate(:page => params[:page], :per_page => 10).order('nombre ASC')
    @cantidad = Tipologia.count
  end

  # GET /tipologias/1
  # GET /tipologias/1.json
  def show
  end

  # GET /tipologias/new
  def new
    @tipologia = Tipologia.new
  end

  # GET /tipologias/1/edit
  def edit
  end

  # POST /tipologias
  # POST /tipologias.json
  def create
    @tipologia = Tipologia.new(tipologia_params)

    respond_to do |format|
      if @tipologia.save
        format.html { redirect_to @tipologia, notice: 'Tipologia è stato creato con successo.' }
        format.json { render action: 'show', status: :created, location: @tipologia }
      else
        format.html { render action: 'new' }
        format.json { render json: @tipologia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipologias/1
  # PATCH/PUT /tipologias/1.json
  def update
    respond_to do |format|
      if @tipologia.update(tipologia_params)
        format.html { redirect_to @tipologia, notice: 'Tipologia è stato aggiornato con successo.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tipologia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipologias/1
  # DELETE /tipologias/1.json
  def destroy
    @tipologia.destroy
    respond_to do |format|
      format.html { redirect_to tipologias_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipologia
      @tipologia = Tipologia.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipologia_params
      params.require(:tipologia).permit(:nombre)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tipologias_helper.rb
module TipologiasHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/tipologias/_form.html.erb
<%= form_for(@tipologia) do |f| %>
  <% if @tipologia.errors.any? %>
    <div id="error_explanation">
      <h2><%=raw t('errors.template.header', count: @tipologia.errors.count, model: "tipologia") %></h2>

      <ul>
      <% @tipologia.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit t('.submit'), class:"btn btn-default" %>
  </div>
<% end %>

app/views/tipologias/edit.html.erb
<div class="panel-heading">
	<%= link_to content_tag(:span, '', class: 'glyphicon glyphicon-chevron-left'), tipologias_path, class: "lnk_back", title: 'Ritorno' %> &nbsp;&nbsp;
	Modifica Tipologia
</div>
<div class="table-responsive">
<%= render 'form' %>
<%= link_to 'Mostrare', @tipologia, class: "btn btn-primary", id: "color-blanco" %>
</div>

app/views/tipologias/index.html.erb
<div class="panel-heading" id="panel-heading-sep">Elenco Tipologia</div>

<div class="table-responsive">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th></th>
      <% if params[:permiso_edit] %><th></th><% end %>
      <% if params[:permiso_delete] %><th></th><% end %>
    </tr>
  </thead>

  <tbody>
    <% @tipologias.each do |tipologia| %>
      <tr>
        <td><%= tipologia.nombre %></td>
        <td><%= link_to content_tag(:span, '', class: 'glyphicon glyphicon-folder-open'), tipologia, title: 'Mostrare', id: "acciones" %></td>
        <% if params[:permiso_edit] %><td><%= link_to content_tag(:span, '', class: 'glyphicon glyphicon-edit'), edit_tipologia_path(tipologia), title: 'Modifica', id: "acciones" %></td><% end %>
        <% if params[:permiso_delete] %><td><%= link_to content_tag(:span, '', class: 'glyphicon glyphicon-remove'), tipologia, title: 'Eliminare', id: "acciones", method: :delete, data: { confirm: 'Sei sicuro?' } %></td><% end %>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td>Totale Tipologia: <b><%= @cantidad %></b></td>
    </tr>
  </tfoot>
</table>
</div>
<br>
<div class="form-actions">
  <div class="row">
    <div class="col-md-8"><%= will_paginate @tipologias, renderer: BootstrapPagination::Rails, :previous_label => "<<", :next_label => ">>" %></div>
    <% if params[:permiso_new] %><div class="col-md-4"><p class="text-right"><%= link_to 'Nuovo Tipologia', new_tipologia_path, class: 'btn btn-primary btn-sm', id: 'color-blanco' %></p></div><% end %>
  </div>
</div>

app/views/tipologias/new.html.erb
<div class="panel-heading">
	<%= link_to content_tag(:span, '', class: 'glyphicon glyphicon-chevron-left'), tipologias_path, class: "lnk_back", title: 'Ritorno' %> &nbsp;&nbsp;
	Nuovo Tipologia
</div>
<div class="table-responsive">
<%= render 'form' %>
<%= link_to 'Ritorno', tipologias_path, class: "btn btn-default" %>
</div>

app/views/tipologias/show.html.erb
<div class="panel-heading">
	<%= link_to content_tag(:span, '', class: 'glyphicon glyphicon-chevron-left'), tipologias_path, class: "lnk_back", title: 'Ritorno' %> &nbsp;&nbsp;
	Tipologia dettagli <%= @tipologia.nombre %>
</div>
<div class="table-responsive">
<p>
  <strong>Nome:</strong>
  <%= @tipologia.nombre %>
</p>
<% if params[:permiso_edit] %><%= link_to 'Modifica', edit_tipologia_path(@tipologia), class: "btn btn-primary", id: "color-blanco" %><% end %>
</div>